[project]
name = "hector-ai"
version = "0.1.9"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.97.0",
    "cryptography>=42.0.0",
    "google-genai>=1.73.1",
    "openai>=2.32.0",
    "pyside6>=6.11.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
